server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-circular-references: true
  profiles:
    #active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 187307492269-lpe7ok7ko1idf1o49cmvq3l94jjt9vhl.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

          facebook:
            client-id: 1714050492098687
            client-secret: 9a0fa8109dca2bc38d6538c46f9f4a51
            scope:
              - email
              - public_profile

          naver:
            client-id: iHoqHBfn_FIQb2jztmz4
            client-secret: S9wKwWGTik
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #응답받을주소 설정 네이버는 provider가 제공이 안되기 때문에 써줘야함.

        provider:
          naver:
            authorization-uri: https://nid.naver.com/ouath2.0/authorize
            token-uri: https://nid.naver.com/ouath2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attributes: response # 회원 정보를 json으로 받는데 키값으로 네이버가 리턴해줌