server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# ssl 관련설정
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12 #src/main/resources 에 key 파일 생성
#    key-store-password: #키파일 password
#    key-store-type: PKCS12
#    key-alias: bns-ssl

spring:
  mustache:
    expose-spring-macro-helpers: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    remote:
      restart:
        enabled: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    # 데이터베이스 관련 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.hy.demo.Config.Dialect.CustomH2Dialect
        show_sql: true
        format_sql: true
        use_sql_commnets: true
    database-platform: org.hibernate.dialect.H2Dialect



  security:
    oauth2:
      client:
        registration:
          # google 로그인 api 설정
          google:
            client-id: # 클라이언트Id
            client-secret: # key
            scope:
              - email
              - profile

          # facebook 로그인 api 설정
          facebook:
            client-id: # 클라이언트Id
            client-secret: #key
            scope:
              - email
              - public_profile

          # naver 로그인 api 설정
          naver:
            client-id: # 클라이언트Id
            client-secret: # key
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #응답주소 설정

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  # 메일 관련 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: #구글아이디
    password: #비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true