server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  ssl: #https 적용시
#    enabled: true
#    key-store: classpath:keystore.p12 #src/main/resources 에 key 파일 생성
#    key-store-password: #키파일 password
#    key-store-type: PKCS12
#    key-alias: bns-ssl


spring:
  mustache:
    expose-spring-macro-helpers: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    remote:
      restart:
        enabled: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
   driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.hy.demo.Config.Dialect.CustomH2Dialect
        show_sql: true
        format_sql: true
        use_sql_commnets: true
    database-platform: org.hibernate.dialect.H2Dialect



  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
            - email
            - profile

          facebook:
            client-id:
            client-secret:
            scope:
              - email
              - public_profile

          naver:
            client-id:
            client-secret:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #응답받을주소 설정 네이버는 provider가 제공이 안되기 때문에 써줘야함.

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response